name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  tf_jobs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./  # Change this if your Terraform files are in a subfolder
    permissions:
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    # AWS Login - Configure AWS credentials from GitHub Secrets
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Add your AWS Access Key ID in GitHub Secrets
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Add your AWS Secret Access Key in GitHub Secrets
        aws-region: "us-east-1"  # Change to your desired region (e.g., us-west-2, eu-west-1, etc.)

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: plan
      run: terraform plan
      continue-on-error: true
